### ISSUE TITLE
list class not allowed in pydantic nested schema default

### ISSUE THREAD

**Issue by dada-engineer** [jpmorganchase/py-avro-schema#68]
I have a class of type pydantic.BaseModel with a chiled pydantic Basemodel with a list attribute.

This is not serializable right now

```
import pydantic


class Bar(pydantic.BaseModel):
    baz: list[str] = pydantic.Field(default_factory=list)


class Foo(pydantic.BaseModel):
    bar: Bar = pydantic.Field(default_factory=Bar)


print(pas.generate(Foo))
```

Traceback:

```
import py_avro_schema as pas

import pydantic


class Bar(pydantic.BaseModel):
    baz: list[str] = pydantic.Field(default_factory=list)


class Foo(pydantic.BaseModel):
    bar: Bar = pydantic.Field(default_factory=Bar)


print(pas.generate(Foo))


Traceback (most recent call last):
  File "/Users/dada_engineer/workspace/private/py-avro-schema/example.py", line 14, in <module>
    print(pas.generate(Foo))
  File "/Users/dada_engineer/workspace/private/py-avro-schema/.venv/lib/python3.9/site-packages/memoization/caching/plain_cache.py", line 42, in wrapper
    result = user_function(*args, **kwargs)
  File "/Users/dada_engineer/workspace/private/py-avro-schema/src/py_avro_schema/__init__.py", line 64, in generate
    schema_dict = schema(py_type, namespace=namespace, options=options)
  File "/Users/dada_engineer/workspace/private/py-avro-schema/src/py_avro_schema/_schemas.py", line 139, in schema
    schema_data = schema_obj.data(names=names)
  File "/Users/dada_engineer/workspace/private/py-avro-schema/src/py_avro_schema/_schemas.py", line 695, in data
    return self.data_before_deduplication(names=names)
  File "/Users/dada_engineer/workspace/private/py-avro-schema/src/py_avro_schema/_schemas.py", line 766, in data_before_deduplication
    "fields": [field.data(names=names) for field in self.record_fields],
  File "/Users/dada_engineer/workspace/private/py-avro-schema/src/py_avro_schema/_schemas.py", line 766, in <listcomp>
    "fields": [field.data(names=names) for field in self.record_fields],
  File "/Users/dada_engineer/workspace/private/py-avro-schema/src/py_avro_schema/_schemas.py", line 826, in data
    field_data["default"] = self.schema.make_default(self.default)
  File "/Users/dada_engineer/workspace/private/py-avro-schema/src/py_avro_schema/_schemas.py", line 908, in make_default
    return {key: _schema_obj(value.__class__).make_default(value) for key, value in py_default}
  File "/Users/dada_engineer/workspace/private/py-avro-schema/src/py_avro_schema/_schemas.py", line 908, in <dictcomp>
    return {key: _schema_obj(value.__class__).make_default(value) for key, value in py_default}
  File "/Users/dada_engineer/workspace/private/py-avro-schema/src/py_avro_schema/_schemas.py", line 162, in _schema_obj
    raise TypeNotSupportedError(f"Cannot generate Avro schema for Python type {py_type}")
py_avro_schema._schemas.TypeNotSupportedError: Cannot generate Avro schema for Python type <class 'list'>
```

relates to handling of pydantic defaults in #64

**Comment by dada-engineer** [comment]
@faph this is a problem when having an empty list in defaults. We could not instantiate this sequence schema even if we can detect the type correctly as the constructor requires at least one element in the list.

I'd suggest for now to use schema_obj(value.__class__) only if the value is supported by any schema.

**Comment by dada-engineer** [comment]
Sorry correction, we should just use the pydantic schema annotations instead of value.__class__. Then it works

**Comment by dada-engineer** [comment]
@faph would be great to have this fix quite soon 😊 sorry for the hurry / pushy behaviour 🙈

**Comment by faph** [comment]
That's ok @dada-engineer. Left a few minor comments
